name: pointrestaurant
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  provider: ^4.3.1
  flutter_svg: ^0.17.4
  vertical_tabs: ^0.2.0
  transparent_image: ^1.0.0
  slide_popup_dialog: ^0.0.2
  direct_select: ^1.0.2
  socket_io: ^0.9.4
  bottom_animation: ^1.1.0
  easy_localization: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - assets/fonts/
     - assets/images/
     - assets/icons/

  fonts:
    - family: San-francisco
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
    - family: NothingYouCouldDo
      fonts:
        - asset: assets/fonts/NothingYouCouldDo.ttf
