name: pointrestaurant
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  flutter_svg: ^0.17.4
  vertical_tabs: ^0.2.0
  direct_select: ^1.0.2
  flutter_slidable: ^0.5.5
  easy_localization: ^2.3.3
  platform_action_sheet: ^0.0.3
  cached_network_image: ^2.1.0
  intl: ^0.16.1
  flutter_collapse: ^0.1.1
  blue_thermal_printer: ^1.0.8
  network_image_to_byte: ^0.0.1
  path_provider: ^1.6.11
  flutter_launcher_icons: ^0.8.0
  image: ^2.1.12
  esc_pos_utils: ^0.4.8
  esc_pos_printer: ^3.2.8
  toggle_switch: "^0.1.8"
  slide_digital_clock: ^1.0.0
  url_launcher: any
  connectivity: any


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main.png"    
flutter:

  uses-material-design: true
  assets:
     - assets/fonts/
     - assets/images/
     - assets/icons/

  fonts:
    - family: San-francisco
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
   